#!/bin/bash
# Run from root folder

cd ..

if [ ! -d boost_graph_cookbook_1 ]; then
  git clone https://github.com/richelbilderbeek/boost_graph_cookbook_1
fi

if [ ! -d GSL ]; then
  git clone https://github.com/Microsoft/GSL
fi

if [ ! -d gausser ]; then
  git clone https://github.com/richelbilderbeek/gausser
fi

if [ ! -d Newick ]; then
  git clone https://github.com/richelbilderbeek/Newick
fi

if [ ! -d SurfacePlotter ]; then
  git clone https://github.com/richelbilderbeek/SurfacePlotter
fi

if [ ! -d RibiClasses ]; then
  git clone https://github.com/richelbilderbeek/RibiClasses
fi

if [ ! -d RibiLibraries ]; then
  git clone https://github.com/richelbilderbeek/RibiLibraries
fi

if [ ! -d RibiUnits ]; then
  git clone https://github.com/richelbilderbeek/RibiUnits
fi

cd daisieme
./scripts/pull_other_githubs