// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dme_create_params_file_cpp
void dme_create_params_file_cpp(const std::string& filename, const double ana_psr, const double clado_is_psr, const double clado_main_psr, const double ext_is_psr);
RcppExport SEXP _daisieme_dme_create_params_file_cpp(SEXP filenameSEXP, SEXP ana_psrSEXP, SEXP clado_is_psrSEXP, SEXP clado_main_psrSEXP, SEXP ext_is_psrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const double >::type ana_psr(ana_psrSEXP);
    Rcpp::traits::input_parameter< const double >::type clado_is_psr(clado_is_psrSEXP);
    Rcpp::traits::input_parameter< const double >::type clado_main_psr(clado_main_psrSEXP);
    Rcpp::traits::input_parameter< const double >::type ext_is_psr(ext_is_psrSEXP);
    dme_create_params_file_cpp(filename, ana_psr, clado_is_psr, clado_main_psr, ext_is_psr);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_daisieme_dme_create_params_file_cpp", (DL_FUNC) &_daisieme_dme_create_params_file_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_daisieme(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
