# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a parameter file.
#' @param filename name of the file
#' @return nothing
#' @author Richel J.C. Bilderbeek
#' @export
dme_create_params_file_cpp <- function(filename) {
    invisible(.Call(`_daisieme_dme_create_params_file_cpp`, filename))
}

